$(document).ready(function(){
	//模式切换
	$(".kuai-icon").click(function(){
       $(".lesson-list2").hide()
       $(".lesson-list").show(200);
    });
	$(".list-icon").click(function(){
       $(".lesson-list").hide()
       $(".lesson-list2").show(200)
    });
    //中部hover变化
    $(".lesson-list .lesson-infor").mouseenter(function(){
		$(this).css({
			height:"178px"
		});
	});
	$(".lesson-list .lesson-infor").mouseleave(function(){
		$(this).css({
			height:"88px"
		});
	});
	$(".t1").mouseenter(function(){
		$(".h1").css({
			height:"178px"
		});
		$(".wordchange1").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t1").mouseleave(function(){
		$(".h1").css({
			height:"88px"
		});
		$(".wordchange1").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t2").mouseenter(function(){
		$(".2").css({
			height:"178px"
		});
		$(".wordchange2").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t2").mouseleave(function(){
		$(".h2").css({
			height:"88px"
		});
		$(".wordchange2").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t3").mouseenter(function(){
		$(".h3").css({
			height:"178px"
		});
		$(".wordchange3").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t3").mouseleave(function(){
		$(".h3").css({
			height:"88px"
		});
		$(".wordchange3").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t4").mouseenter(function(){
		$(".h4").css({
			height:"178px"
		});
		$(".wordchange4").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t4").mouseleave(function(){
		$(".h4").css({
			height:"88px"
		});
		$(".wordchange4").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t5").mouseenter(function(){
		$(".h5").css({
			height:"178px"
		});
		$(".wordchange5").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t5").mouseleave(function(){
		$(".h5").css({
			height:"88px"
		});
		$(".wordchange5").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t6").mouseenter(function(){
		$(".h6").css({
			height:"178px"
		});
		$(".wordchange6").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t6").mouseleave(function(){
		$(".h6").css({
			height:"88px"
		});
		$(".wordchange6").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t7").mouseenter(function(){
		$(".h7").css({
			height:"178px"
		});
		$(".wordchange7").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t7").mouseleave(function(){
		$(".h7").css({
			height:"88px"
		});
		$(".wordchange7").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t8").mouseenter(function(){
		$(".h8").css({
			height:"178px"
		});
		$(".wordchange8").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t8").mouseleave(function(){
		$(".h8").css({
			height:"88px"
		});
		$(".wordchange8").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t9").mouseenter(function(){
		$(".h9").css({
			height:"178px"
		});
		$(".wordchange9").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t9").mouseleave(function(){
		$(".h9").css({
			height:"88px"
		});
		$(".wordchange9").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t10").mouseenter(function(){
		$(".h10").css({
			height:"178px"
		});
		$(".wordchange10").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t10").mouseleave(function(){
		$(".h10").css({
			height:"88px"
		});
		$(".wordchange10").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t11").mouseenter(function(){
		$(".h11").css({
			height:"178px"
		});
		$(".wordchange11").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t11").mouseleave(function(){
		$(".h11").css({
			height:"88px"
		});
		$(".wordchange11").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".t12").mouseenter(function(){
		$(".h12").css({
			height:"178px"
		});
		$(".wordchange12").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".t12").mouseleave(function(){
		$(".h12").css({
			height:"88px"
		});
		$(".wordchange12").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h1").mouseenter(function(){
		$(".wordchange1").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h1").mouseleave(function(){
		$(".wordchange1").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h2").mouseenter(function(){
		$(".wordchange2").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h2").mouseleave(function(){
		$(".wordchange2").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h3").mouseenter(function(){
		$(".wordchange3").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h3").mouseleave(function(){
		$(".wordchange3").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h4").mouseenter(function(){
		$(".wordchange4").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h4").mouseleave(function(){
		$(".wordchange4").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h5").mouseenter(function(){
		$(".wordchange5").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h5").mouseleave(function(){
		$(".wordchange5").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h6").mouseenter(function(){
		$(".wordchange6").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h6").mouseleave(function(){
		$(".wordchange6").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h7").mouseenter(function(){
		$(".wordchange7").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h8").mouseleave(function(){
		$(".wordchange8").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h9").mouseenter(function(){
		$(".wordchange9").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h9").mouseleave(function(){
		$(".wordchange9").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h10").mouseenter(function(){
		$(".wordchange10").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h10").mouseleave(function(){
		$(".wordchange10").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h11").mouseenter(function(){
		$(".wordchange11").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h11").mouseleave(function(){
		$(".wordchange11").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	$(".h12").mouseenter(function(){
		$(".wordchange12").css({
			display:"block",
			overflow:"visible",
			opacity:"1"
		})
	});
	$(".h12").mouseleave(function(){
		$(".wordchange12").css({
			display:"none",
			overflow:"hidden",
			opacity:"0"
		})
	});
	
	
	// $(".lesson-list .img").mouseleave(function(){
	// 	$(".lesson-infor").css({
	// 		height:"88px"
	// 	});
	// });
	//回到顶部
	$(".gotop").click(function () {
        var speed=200;//滑动的速度
        $('body,html').animate({ scrollTop: 0 }, speed);
        return false;
    });
    //左侧二级菜单
    $(".s0").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"block"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s1").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"block"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s2").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"block"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s3").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"block"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s4").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"block"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s5").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"block"
		})
	});
	$(".s6").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"block"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s7").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"block"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s8").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"block"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"block"
		})
		$(".sheji").css({
			display:"none"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$(".s9").mouseenter(function(){
    	$(".list-show").css({
			display:"block"
		});
		$(".yidong").css({
			display:"none"
		});
		$(".qianduan").css({
			display:"none"
		})
		$(".houduan").css({
			display:"none"
		})
		$(".jichu").css({
			display:"none"
		})
		$(".yunjisuan").css({
			display:"none"
		})
		$(".shujuku").css({
			display:"none"
		})
		$(".renzhengkaoshi").css({
			display:"none"
		})
		$(".IT").css({
			display:"none"
		})
		$(".sheji").css({
			display:"block"
		})
		$(".zhinengyingjian").css({
			display:"none"
		})
	});
	$("#aside").mouseleave(function(){
		$(".list-show").hide()
	})
	//搜索框
	$(".icon-box").click(function(){
		$("nav").hide(),
		$(".icon-box").hide(),
		$(".searchbox").show(200)
	});
	$("#close-btn").click(function(){
		$("nav").show(),
		$(".icon-box").show(),
		$(".searchbox").hide()
	});
	

});